### ISSUE TITLE
NoMethodError: undefined method `keys' for "OtherField":String

### ISSUE THREAD

**Issue by richymontz** [DripEmail/drip-ruby#30]
I had an error when I try to do a request to get `custom_fields` from my Drip account.
This is the code line: `client.get("#{client.account_id}/custom_field_identifiers", {})`, "OtherField" is one of my custom fields

**Comment by rdunlop** [comment]
I have run into this today too. the `custom_fields` call does not appear to work.

The curl command works fine though.
```
curl "https://api.getdrip.com/v2/<redacted>/custom_field_identifiers"  -H 'User-Agent: Your App Name (www.yourapp.com)' -u <redacted>:
{"custom_field_identifiers":["First_name","Last_name","first_name","last_name"]}
````

but calling `client.custom_fields` causes:
`NoMethodError (undefined method `keys' for "First_name":String)`

**Comment by will-in-wi** [comment]
I'm having some trouble reproducing. Is this still an issue in the latest version?

**Comment by eterry1388** [comment]
Reproduced. 

This code (taken directly from documentation [here](https://developer.drip.com/?ruby#custom-fields)) raises an exception.
 
```ruby
require 'drip'

client = Drip::Client.new do |c|
  c.api_key = "YOUR API KEY"
  c.account_id = "YOUR_ACCOUNT_ID"
end

response = client.custom_fields . # <- Exception occurs here
```

Exception:

```
/Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/resource.rb:32:in `block in process': undefined method `keys' for "first_name":String (NoMethodError)
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/resource.rb:31:in `tap'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/resource.rb:31:in `process'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/resource.rb:9:in `initialize'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/collection.rb:27:in `new'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/collection.rb:27:in `block in parse_items'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/collection.rb:26:in `map'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/collection.rb:26:in `parse_items'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/collection.rb:9:in `initialize'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/response.rb:59:in `new'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/response.rb:59:in `block (2 levels) in parse_members'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/response.rb:52:in `each'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/response.rb:52:in `block in parse_members'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/response.rb:50:in `tap'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/response.rb:50:in `parse_members'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/response.rb:13:in `initialize'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/client.rb:119:in `new'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/client.rb:119:in `build_response'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/client.rb:85:in `make_request'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/client.rb:61:in `get'
  from /Users/ericterry/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/drip-ruby-3.1.1/lib/drip/client/custom_fields.rb:9:in `custom_fields'
```

To reproduce, be sure you have custom fields on the account.
