### ISSUE TITLE
TypeError: can't dup Fixnum

### ISSUE THREAD

**Issue by benwoodward** [DripEmail/drip-ruby#32]
Can't figure out whether this is an issue with our code, or the gem code. Hoping someone can shed some light on what might be going on here. 

```
TypeError: can't dup Fixnum
  app/services/drip_service.rb:10:in `create_or_update_contact'
    @client.create_or_update_subscriber(contact.email,
  app/models/newsletter_contact.rb:50:in `sync'
    DripService.new.create_or_update_contact(self, tags, remove_tags, merged_custom_fields)
  app/models/newsletter_contact.rb:37:in `sync_contact'
    sync
  app/models/newsletter_contact.rb:28:in `update_contact'
    contact.sync_contact
  app/models/subscription_box_count_history.rb:48:in `tag_contact'
    NewsletterContact.update_contact tags: ["customer"], remove_tags: ["cancelled_customer"], user: user
```

```ruby
class DripService
  def initialize
    @client = Drip::Client.new do |c|
      c.api_key = ENV["DRIP_KEY"]
      c.account_id = ENV["DRIP_ACCOUNT_ID"]
    end
  end

  def create_or_update_contact(contact, tags=[], remove_tags=[], custom_fields={})
    @client.create_or_update_subscriber(contact.email,
                                        tags: include_env_tag(tags),
                                        remove_tags: remove_tags,
                                        custom_fields: custom_fields)
  end
end
```

```ruby
class NewsletterContact
  include ActiveModel::Model
  include Virtus.model

  attribute :id,                   Integer
  attribute :first_name,           String
  attribute :last_name,            String
  attribute :email,                String
  attribute :tags,                 Array
  attribute :remove_tags,          Array
  attribute :reward_code,          String
  attribute :referred_friend_name, String
  attribute :ticked_subscribe_to_newsletter_at_signup, Boolean
  attribute :custom_fields,        Hash

  validates :email, presence: true
  validates_format_of :email, :with => Devise::email_regexp

  def self.update_contact(tags:[], remove_tags:[], user:, custom_fields: {})
    begin
      contact = NewsletterContact.new
      contact.id = user.id
      contact.first_name = user.first_name if user.first_name
      contact.email = user.email
      contact.tags = tags
      contact.remove_tags = remove_tags
      contact.custom_fields = custom_fields
      contact.sync_contact

    rescue InvalidContactError => e
      Raven.capture_exception(e)
    end
  end

  def sync_contact
    if valid?
      sync
      true
    else
      raise InvalidContactError.new(errors.full_messages)
      false
    end
  end

  private

  def sync
    DripService.new.create_or_update_contact(self, tags, remove_tags, merged_custom_fields)
  end

  def merged_custom_fields
    default_fields = {}

    default_fields[:first_name] = self.first_name.titleize if self.first_name
    default_fields[:last_name] = self.last_name.titleize if self.last_name
    default_fields[:user_id] = self.id if self.id
    default_fields[:reward_code] = self.reward_code.upcase if self.reward_code
    default_fields[:referred_friend_name] = self.referred_friend_name.titleize if self.referred_friend_name
    default_fields[:ticked_subscribe_to_newsletter_at_signup] = self.ticked_subscribe_to_newsletter_at_signup if self.ticked_subscribe_to_newsletter_at_signup

    default_fields.merge(custom_fields)
  end
end
```

```
NewsletterContact.update_contact tags: ["customer"], remove_tags: ["cancelled_customer"], user: user
```

**Comment by tekin** [comment]
I'm also see this error.

**Comment by djreimer** [comment]
Thanks for reporting this @tekin @benwoodward.

@samudary -- can you take a look please? Thanks!

**Comment by will-in-wi** [comment]
I'm having a tough time reproducing this on v3.0.0. My reproduction case is:

```ruby
client = Drip::Client.new do |c|
  c.api_key = "MYKEY"
  c.account_id = 1234567
end

client.create_or_update_subscriber("myemail@example.com",
  tags: ["customer"],
  remove_tags: ["cancelled_customer"],
  custom_fields: {
    first_name: "Jane",
    last_name: "Doe",
    user_id: 12345,
    reward_code: "ABCDE",
    referred_friend_name: "John Doe",
    ticked_subscribe_to_newsletter_at_signup: true,
  })
```

Is this still an issue, or am I missing something?

Thanks!

**Comment by tekin** [comment]
we do still see this error happening (last happened 7 days ago), but for context we were only able to run drip-ruby 0.0.11 because the oauth gem depends on `faraday < 0.13` and drip-ruby used to have an explicit dependency of `faraday ~> 0.13`. It looks like drip-ruby no longer depends on faraday, so we might be able to update drip-ruby now.

**Comment by will-in-wi** [comment]
That makes sense. If you could update to 3.0.0 and let me know if it is still an issue, that'd help. Otherwise, I'll see if I can reproduce in 0.0.11. Thanks!

**Comment by will-in-wi** [comment]
I can't reproduce this on 0.0.11 with the reproduction case in https://github.com/DripEmail/drip-ruby/issues/32#issuecomment-392850517 or trying to rebuild the test case in the original posting. Could you post a reduced test case that reproduces this?
