### ISSUE TITLE
Enable logging

### ISSUE THREAD

**Issue by OleMchls** [DripEmail/drip-ruby#33]
I am currently debugging a case of
```
gems/drip-ruby-0.0.12/lib/drip/resource.rb:32:in `block in process': undefined method `keys' for 500:Integer (NoMethodError)
```
I assume the API is returning an unexpected value. But in order to prove this, I needed request/response logging. For now, I helped myself with 

```ruby
Drip::Client.new do |c|
  c.api_key = @api_key
  c.account_id = @account_id
  c.connection.response(:logger, Rails.logger, headers: true, bodies: true)
end
```

This is not an ideal solution and it would be great to have this gem to support a more specific logging.

Full trace:
<details>

```
gems/drip-ruby-0.0.12/lib/drip/resource.rb:32:in `block in process': undefined method `keys' for 500:Integer (NoMethodError)
    from gems/drip-ruby-0.0.12/lib/drip/resource.rb:31:in `tap'
    from gems/drip-ruby-0.0.12/lib/drip/resource.rb:31:in `process'
    from gems/drip-ruby-0.0.12/lib/drip/resource.rb:9:in `initialize'
    from gems/drip-ruby-0.0.12/lib/drip/response.rb:59:in `new'
    from gems/drip-ruby-0.0.12/lib/drip/response.rb:59:in `block (2 levels) in parse_members'
    from gems/drip-ruby-0.0.12/lib/drip/response.rb:52:in `each'
    from gems/drip-ruby-0.0.12/lib/drip/response.rb:52:in `block in parse_members'
    from gems/drip-ruby-0.0.12/lib/drip/response.rb:50:in `tap'
    from gems/drip-ruby-0.0.12/lib/drip/response.rb:50:in `parse_members'
    from gems/drip-ruby-0.0.12/lib/drip/response.rb:13:in `initialize'
    from gems/drip-ruby-0.0.12/lib/drip/client.rb:70:in `new'
    from gems/drip-ruby-0.0.12/lib/drip/client.rb:70:in `build_response'
    from gems/drip-ruby-0.0.12/lib/drip/client.rb:55:in `make_request'
    from gems/drip-ruby-0.0.12/lib/drip/client.rb:43:in `post'
    from gems/drip-ruby-0.0.12/lib/drip/client/subscribers.rb:49:in `create_or_update_subscriber'
```

</details>

**Comment by will-in-wi** [comment]
At this point, we're going to not implement this. Byebug, Wireshark/tcpdump, and other similar tools can usually suffice to debug this case.

Thanks for the suggestion!

**Comment by OleMchls** [comment]
>At this point, we're going to not implement this. Byebug, Wireshark/tcpdump, and other similar tools can usually suffice to debug this case.

This is only true when you can reproduce the bug, in order to reproduce a bug I'd need to know what was sent/received. We see the error linked in the initial report every once in a while 

- May 23rd, 05:02:21 UTC
- May 23rd, 04:56:21 UTC
- Apr 27th, 17:30:47 UTC
- Apr 7th, 19:22:42 UTC
- Apr 6th, 03:00:55 UTC
- Mar 28th, 15:21:24 UTC
- Mar 24th, 20:22:28 UTC
- Mar 20th, 15:43:33 UTC
- Mar 20th, 13:36:55 UTC
- Mar 12th, 07:21:46 UTC
- Mar 11th, 06:09:33 UTC
- Mar 10th, 21:07:45 UTC
- Mar 6th, 21:56:23 UTC
- Mar 6th, 21:55:56 UTC
- Mar 6th, 21:52:24 UTC

 and cannot reproduce it without knowing more details about the request and the response.

**Comment by will-in-wi** [comment]
Could you upgrade to drip-ruby 3.0 and then post the backtrace in a new issue? At a bare minimum, this error message is not especially helpful, and I'd like to confirm it is fixed.

**Comment by will-in-wi** [comment]
Also, would something like https://github.com/trusche/httplog help your case?
